<div class="ui cards">
    <div class="card">
        <div class="content">
            <b>友情链接</b>
            <div class="ui divider"></div>
            <div class="ui list">
                <div class="item">
                    <a href="http://fedvic.com" target="_blank" title="vic's post">
                        <img src="http://fedvic.com/avatar.jpg" alt="vic's post">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
